language: c++

sudo: off

install:
  - ./interpreter/meta/travis/install-ocaml.sh
  - pip install sphinx

script:
  - ./interpreter/meta/travis/build-test.sh
  - bash ./document/travis-deploy.sh

os: linux

env:
  global:
    - ENCRYPTION_LABEL: "304454be9d6c"
    - COMMIT_AUTHOR_EMAIL: "noreply@webassembly.org"
